-- docs:
-- https://github.com/typescript-language-server/typescript-language-server#running-the-language-server
return {
    -- autostart = false,
    -- Demo: Callback invoked by Nvim's built-in client when attaching a buffer to a language server.
    -- on_attach = function(client)
    --     -- override settings
    --     client.server_capabilities.documentFormattingProvider = false
    --     client.server_capabilities.documentRangeFormattingProvider = false
    --     print('LSP: ' .. client.name)
    --     print(vim.inspect(client.server_capabilities))
    -- end
    -- -- does work either
    -- settings = {
    --     tsserver = {
    --         codeActionsOnSave = {
    --             ["source.organizeImports"] = true,
    --         }
    --     }
    -- }
}
